Repository vention-js-lab/ventioners-stayhub-backend, pull requests merged in 2024-11, with the labels that each got.

#2 [Davranbek Jenisbaev]: Implemented User CRUD and Setup config and validation
  README.md
  package-lock.json
  package.json
  src/app.controller.spec.ts
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/database/database.module.ts
  src/database/migrations/1730919143524-create-user.ts
  src/entities/index.ts
  src/main.ts
  src/modules/users/constants/users-sort-params.constant.ts
  src/modules/users/dto/request/create-user.dto.ts
  src/modules/users/dto/request/index.ts
  src/modules/users/dto/request/update-user.dto.ts
  src/modules/users/dto/request/user-search-params.dto.ts
  src/modules/users/entities/user.entity.ts
  src/modules/users/test/users.controller.spec.ts
  src/modules/users/test/users.mock.ts
  src/modules/users/test/users.service.spec.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.module.ts
  src/modules/users/users.repository.ts
  src/modules/users/users.service.ts
  src/shared/configs/data-source.config.ts
  src/shared/configs/env.config.ts
  src/shared/configs/index.ts
  src/shared/configs/validation.config.ts
  src/shared/constants/index.ts
  src/shared/constants/user-role.constant.ts
  src/shared/decorators/index.ts
  src/shared/decorators/transform-to-int.decorator.ts
  src/shared/libs/hasher.lib.ts
  src/shared/libs/index.ts
  src/shared/pipes/index.ts
  src/shared/pipes/parse-uuid-v4.pipe.ts
Labels: enhancement

#4 [IT]: feat: add google authenticaton
  package-lock.json
  package.json
  src/app.module.ts
  src/modules/index.ts
  src/modules/oAuth/dtos/google-user-create.dto.ts
  src/modules/oAuth/dtos/index.ts
  src/modules/oAuth/guards/google-oauth.guard.ts
  src/modules/oAuth/index.ts
  src/modules/oAuth/oAuth.controller.ts
  src/modules/oAuth/oAuth.module.ts
  src/modules/oAuth/oAuth.service.ts
  src/modules/oAuth/strategies/google.strategy.ts
  src/shared/configs/env.config.ts
  src/shared/decorators/user.decorator.ts
  src/shared/helpers/index.ts
  src/shared/index.ts
Labels: enhancement

#5 [Davranbek Jenisbaev]: Swagger setup and api docs for user crud
  src/main.ts
  src/modules/users/decorators/swagger.decorator.ts
  src/modules/users/dto/request/create-user.dto.ts
  src/modules/users/dto/request/update-user.dto.ts
  src/modules/users/dto/request/user-search-params.dto.ts
  src/modules/users/dto/response/get-users.dto.ts
  src/modules/users/dto/response/index.ts
  src/modules/users/dto/response/user.dto.ts
  src/modules/users/users.controller.ts
Labels: documentation

#9 [DJ][FEAT-23] Redis Integration
  .env.example
  docker-compose.yml
  package-lock.json
  package.json
  src/app.module.ts
  src/redis/redis.module.ts
  src/redis/redis.service.ts
  src/shared/configs/env.config.ts
  src/shared/helpers/index.ts
  src/shared/helpers/json.helper.ts
Labels: enhancement

#14 [DJ][FEAT-28]: Added seeding for Amenities and Categories and updated their tables
  package-lock.json
  package.json
  src/database/data/accommodation-amenities.data.ts
  src/database/data/accommodation-categories.data.ts
  src/database/migrations/1731934120969-update-category-amenity-table.ts
  src/database/run-seed.ts
  src/database/seeders/accommodation-amenity.seeder.ts
  src/database/seeders/accommodation-category.seeder.ts
  src/main.ts
  src/modules/accommodations/entities/amenity.entity.ts
  src/modules/accommodations/entities/category.entity.ts
  src/shared/configs/data-source.config.ts
Labels: enhancement

#16 [DJ][FEAT-32]: Added endpoint for Getting Amenities, Unit Tests and Swagger docs
  src/app.module.ts
  src/database/data/accommodation-amenities.data.ts
  src/database/database.module.ts
  src/database/run-seed.ts
  src/database/seeders/accommodation-amenity.seeder.ts
  src/modules/accommodations/entities/accommodation.entity.ts
  src/modules/accommodations/entities/index.ts
  src/modules/amenities/amenities.controller.ts
  src/modules/amenities/amenities.module.ts
  src/modules/amenities/amenities.service.ts
  src/modules/amenities/decorators/swagger.decorator.ts
  src/modules/amenities/dto/response/amenity.dto.ts
  src/modules/amenities/dto/response/get-amenities.dto.ts
  src/modules/amenities/dto/response/index.ts
  src/modules/amenities/entities/amenity.entity.ts
  src/modules/amenities/entities/index.ts
  src/modules/amenities/test/amenities.controller.spec.ts
  src/modules/amenities/test/amenities.mock.ts
  src/modules/amenities/test/amenities.service.spec.ts
Labels: documentation, enhancement

#19 [D][FEAT-37]: Added endpoint for Getting Wishlisted Accommodations, Unit Tests and Swagger docs
  src/main.ts
  src/modules/users/decorators/swagger.decorator.ts
  src/modules/users/dto/response/get-wishlist.dto.ts
  src/modules/users/test/accommodations.mock.ts
  src/modules/users/test/users.controller.spec.ts
  src/modules/users/test/users.service.spec.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.module.ts
  src/modules/users/users.service.ts
  src/shared/configs/swagger.config.ts
Labels: documentation, enhancement

#20 [AM][FEAT-35]: integrate min.io for object storage
  .env.example
  .gitignore
  docker-compose.yml
  package-lock.json
  package.json
  src/app.module.ts
  src/modules/minio/minio.constants.ts
  src/modules/minio/minio.module.ts
  src/modules/minio/minio.service.ts
  src/shared/configs/env.config.ts
Labels: enhancement

#27 chore: rename like to wishlist
  src/modules/accommodations/accommodations.controller.ts
  src/modules/accommodations/accommodations.service.ts
  src/modules/accommodations/dto/request/index.ts
  src/modules/accommodations/dto/request/wishlist-accommodation.dto.ts
  src/modules/accommodations/tests/accommodation.service.spec.ts
  src/modules/accommodations/tests/accommodations.controller.spec.ts
Labels: invalid

#28 [FIX]: Change response of JWT strategy for refresh tokens
  src/modules/auth/guards/refresh-token.guard.ts
  src/modules/auth/strategies/refresh-token.strategy.ts
Labels: bug

#22 Feat 31/accommodation crud
  src/database/database.module.ts
  src/database/migrations/1732227911346-add-accommodation-owner.ts
  src/database/migrations/1732571561419-create-image.ts
  src/database/migrations/1732720386302-change-user-to-owner.ts
  src/modules/accommodations/accommodations.controller.ts
  src/modules/accommodations/accommodations.module.ts
  src/modules/accommodations/accommodations.service.ts
  src/modules/accommodations/decorators/swagger.decorator.ts
  src/modules/accommodations/dto/request/create-accommodation.dto.ts
  src/modules/accommodations/dto/request/index.ts
  src/modules/accommodations/dto/request/search-accommodation-params.dto.ts
  src/modules/accommodations/dto/request/update-accommodation.dto.ts
  src/modules/accommodations/dto/response/crud-accommodation-response.dto.ts
  src/modules/accommodations/entities/accommodation.entity.ts
  src/modules/accommodations/entities/image.entity.ts
  src/modules/accommodations/entities/index.ts
  src/modules/accommodations/tests/accommodation.service.spec.ts
  src/modules/amenities/amenities.module.ts
  src/modules/amenities/amenities.service.ts
  src/modules/categories/categories.module.ts
  src/modules/categories/categories.service.ts
  src/modules/minio/minio.service.ts
  src/modules/users/entities/user.entity.ts
  src/modules/users/test/users.mock.ts
  src/shared/util/exractFileName.ts
  src/shared/util/urlBuilder.ts
Labels: documentation

#29 [FIX-51]: Update jwt token logic in oAuth module and fix bugs
  src/modules/oAuth/oAuth.controller.ts
  src/modules/oAuth/oAuth.module.ts
  src/modules/oAuth/oAuth.service.ts
  src/modules/oAuth/strategies/google.strategy.ts
Labels: bug

#26 [FEAT-47]: Added bookings module, unit tests and swagger docs
  src/app.module.ts
  src/database/database.module.ts
  src/database/migrations/1732278205426-categories-amenities-seeder.ts
  src/database/migrations/1732608174750-create-booking.ts
  src/database/seeders/accommodation-amenity.seeder.ts
  src/database/seeders/accommodation-category.seeder.ts
  src/modules/accommodations/accommodations.module.ts
  src/modules/accommodations/accommodations.service.ts
  src/modules/accommodations/dto/request/create-accommodation.dto.ts
  src/modules/accommodations/dto/request/search-accommodation-params.dto.ts
  src/modules/bookings/bookings.controller.ts
  src/modules/bookings/bookings.module.ts
  src/modules/bookings/bookings.service.ts
  src/modules/bookings/constants/bookings-service-fee.constant.ts
  src/modules/bookings/constants/bookings-status-transition.constant.ts
  src/modules/bookings/constants/bookings-status.constant.ts
  src/modules/bookings/constants/index.ts
  src/modules/bookings/decorators/swagger.decorator.ts
  src/modules/bookings/dto/request/bookings-query-params.dto.ts
  src/modules/bookings/dto/request/create-booking.dto.ts
  src/modules/bookings/dto/request/index.ts
  src/modules/bookings/dto/request/update-booking-status.dto.ts
  src/modules/bookings/dto/response/booking.dto.ts
  src/modules/bookings/dto/response/create-booking.dto.ts
  src/modules/bookings/dto/response/get-booking.dto.ts
  src/modules/bookings/dto/response/get-my-bookings.dto.ts
  src/modules/bookings/dto/response/index.ts
  src/modules/bookings/dto/response/update-booking-status.dto.ts
  src/modules/bookings/entities/booking.entity.ts
  src/modules/bookings/tests/bookings.controller.spec.ts
  src/modules/bookings/tests/bookings.mock.ts
  src/modules/users/dto/request/user-search-params.dto.ts
  src/shared/decorators/index.ts
  src/shared/transformers/index.ts
  src/shared/transformers/transform-to-date.transformer.ts
  src/shared/transformers/transform-to-number.transformer.ts
  src/shared/transformers/transform-to-upper-case.transformer.ts
  src/shared/transformers/transform-to-year-month-day.transformer.ts
  src/shared/validators/index.ts
  src/shared/validators/is-date-after.validator.ts
  src/shared/validators/is-future-date.validator.ts
Labels: enhancement

#34 [FIX-52]: Updated query in getWishlist to include new image entity
  src/modules/accommodations/entities/accommodation.entity.ts
  src/modules/accommodations/entities/wishlist.entity.ts
  src/modules/users/test/users.service.spec.ts
  src/modules/users/users.service.ts
Labels: bug
