Repository vention-js-lab/ventioners-stayhub-backend, pull requests merged in 2024-12, with the labels that each got.

#31 feat: add an auth endpoint to update the user's password
  src/database/migrations/1732909315405-add-profile-picture-to-user.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.service.ts
  src/modules/auth/dto/request/update-password.dto.ts
  src/modules/minio/minio.service.ts
  src/modules/oAuth/oAuth.controller.ts
  src/modules/users/entities/user.entity.ts
  src/modules/users/test/users.service.spec.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.module.ts
  src/modules/users/users.service.ts
  src/shared/util/urlBuilder.ts
Labels: enhancement

#32 [TEST-50]: Added unit tests for Accommodation Module, Auth Module, OAuth Module and Bookings Module
  package.json
  src/modules/accommodations/accommodations.controller.ts
  src/modules/accommodations/accommodations.module.ts
  src/modules/accommodations/accommodations.service.ts
  src/modules/accommodations/dto/response/accommodation.dto.ts
  src/modules/accommodations/test/accommodations.controller.spec.ts
  src/modules/accommodations/test/accommodations.service.spec.ts
  src/modules/accommodations/test/mock/accommodations.mock.ts
  src/modules/accommodations/test/mock/controller-dependencies.mock.ts
  src/modules/accommodations/test/mock/images.mock.ts
  src/modules/accommodations/test/mock/service-dependencies.mock.ts
  src/modules/accommodations/test/mock/wishlist.mock.ts
  src/modules/accommodations/tests/accommodation.service.spec.ts
  src/modules/accommodations/tests/accommodations.controller.spec.ts
  src/modules/amenities/test/amenities.controller.spec.ts
  src/modules/auth/test/auth.controller.spec.ts
  src/modules/auth/test/auth.service.spec.ts
  src/modules/bookings/bookings.service.ts
  src/modules/bookings/tests/bookings.controller.spec.ts
  src/modules/bookings/tests/bookings.mock.ts
  src/modules/bookings/tests/bookings.service.spec.ts
  src/modules/categories/test/categories.controller.spec.ts
  src/modules/oAuth/test/oAuth.controller.spec.ts
  src/modules/oAuth/test/oAuth.service.spec.ts
  src/modules/users/test/accommodations.mock.ts
  src/modules/users/test/users.controller.spec.ts
  src/modules/users/test/users.service.spec.ts
Labels: enhancement

#39 feat: add getReviewByAccommodationId, did all module and entity relat…
  src/app.module.ts
  src/database/database.module.ts
  src/database/migrations/1733194319627-create-reviews.ts
  src/modules/accommodations/accommodations.service.ts
  src/modules/accommodations/entities/accommodation.entity.ts
  src/modules/accommodations/test/mock/accommodations.mock.ts
  src/modules/reviews/entities/index.ts
  src/modules/reviews/entities/review.entity.ts
  src/modules/reviews/index.ts
  src/modules/reviews/reviews.controller.ts
  src/modules/reviews/reviews.module.ts
  src/modules/reviews/reviews.service.ts
  src/modules/reviews/tests/reviews.controller.spec.ts
  src/modules/reviews/tests/reviews.service.spec.ts
  src/modules/users/entities/user.entity.ts
Labels: enhancement

#40 fix: add reviewer on review both review and getAccommodation
  src/modules/accommodations/accommodations.service.ts
  src/modules/accommodations/test/accommodations.service.spec.ts
  src/modules/reviews/reviews.service.ts
Labels: bug

#42 [FEAT-55]: Setup deployment and CI/CD
  .dockerignore
  .env.example
  .github/workflows/deploy.yml
  Dockerfile
  docker-compose.production.yml
  src/database/database.module.ts
  src/main.ts
  src/modules/accommodations/accommodations.service.ts
  src/modules/minio/minio.constants.ts
  src/modules/users/users.service.ts
  src/shared/configs/data-source.config.ts
  src/shared/configs/env.config.ts
  src/shared/util/urlBuilder.ts
Labels: enhancement

#37 Feat 48/create migration
  src/database/migrations/1732997200697-create-longitude-latitude.ts
  src/modules/accommodations/accommodations.service.ts
  src/modules/accommodations/dto/request/create-accommodation.dto.ts
  src/modules/accommodations/entities/accommodation.entity.ts
  src/modules/accommodations/test/accommodations.controller.spec.ts
  src/modules/accommodations/test/accommodations.service.spec.ts
  src/modules/accommodations/test/mock/accommodations.mock.ts
  src/shared/transformers/index.ts
  src/shared/transformers/transform-to-float.transformer.ts
  src/shared/util/createCordinates.ts
Labels: documentation, enhancement

#44 [FEAT-65]: Added token blacklisting to refresh token rotation
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.module.ts
  src/modules/auth/strategies/refresh-token.strategy.ts
  src/modules/auth/test/auth.controller.spec.ts
  src/modules/oAuth/oAuth.controller.ts
  src/modules/oAuth/oAuth.module.ts
  src/modules/oAuth/test/oAuth.controller.spec.ts
  src/redis/redis.service.ts
  src/shared/decorators/cookies.decorator.ts
Labels: enhancement

#43 feat(60): migration to add number of guests
  src/database/migrations/1733425270645-accommodation-number-of-guests.ts
  src/modules/accommodations/dto/request/create-accommodation.dto.ts
  src/modules/accommodations/dto/request/search-accommodation-params.dto.ts
  src/modules/accommodations/dto/response/accommodation.dto.ts
  src/modules/accommodations/dto/response/crud-accommodation-response.dto.ts
  src/modules/accommodations/entities/accommodation.entity.ts
  src/modules/accommodations/test/accommodations.controller.spec.ts
  src/modules/accommodations/test/accommodations.service.spec.ts
  src/modules/accommodations/test/mock/accommodations.mock.ts
  src/modules/users/dto/request/user-search-params.dto.ts
  src/modules/users/test/accommodations.mock.ts
  src/shared/transformers/index.ts
  src/shared/transformers/transform-to-int.transformer.ts
Labels: enhancement, conflict

#46 [FEAT-62]: Setup cdn, add image compression and blurhash
  .env.example
  package-lock.json
  package.json
  src/database/migrations/1733677537127-add-thumbnail-url-and-blurhash.ts
  src/modules/accommodations/accommodations.controller.ts
  src/modules/accommodations/accommodations.service.ts
  src/modules/accommodations/entities/image.entity.ts
  src/modules/accommodations/pipes/accommodation-images-validation.pipe.ts
  src/modules/accommodations/test/accommodations.controller.spec.ts
  src/modules/accommodations/test/accommodations.service.spec.ts
  src/modules/accommodations/test/mock/example.jpg
  src/modules/users/users.service.ts
  src/shared/configs/env.config.ts
  src/shared/util/urlBuilder.ts
Labels: enhancement

#49 feat: add mail sending
  .env.example
  docker-compose.yml
  package-lock.json
  package.json
  src/app.module.ts
  src/modules/bookings/bookings.service.ts
  src/modules/mail/mail.controller.ts
  src/modules/mail/mail.module.ts
  src/modules/mail/mail.service.ts
  src/shared/configs/env.config.ts
  src/shared/exceptions/index.ts
  src/shared/exceptions/mail-sending.exception.ts
Labels: enhancement

#51 [FEAT-76]: Removed Image Processing and Moved it to AWS Lambda
  .github/workflows/deploy.yml
  src/modules/accommodations/accommodations.service.ts
  src/modules/minio/minio.service.ts
  src/shared/helpers/generate-public-file-url.ts
  src/shared/index.ts
Labels: enhancement

#56 [FIX]: Update public image url
  src/shared/helpers/generate-public-file-url.ts
Labels: enhancement

#55 75 notification
  .env.example
  package-lock.json
  package.json
  src/app.module.ts
  src/modules/bookings/bookings.module.ts
  src/modules/bookings/bookings.service.ts
  src/modules/bookings/tests/bookings.service.spec.ts
  src/modules/mail/mail.controller.ts
  src/modules/mail/mail.module.ts
  src/modules/mail/mail.service.ts
  src/modules/notifications/events/notification.event.ts
  src/modules/notifications/listeners/booking-status.listener.ts
  src/modules/notifications/notification.service.ts
  src/modules/notifications/notificaton.module.ts
  src/shared/configs/env.config.ts
Labels: enhancement

#59 [FEAT-69]: Added review and overall rating to my accommodations response
  src/modules/accommodations/accommodations.service.ts
Labels: enhancement

#60 [FEAT-78]: Added multi-language support for amenities and categories
  src/database/data/accommodation-amenities-v2.data.ts
  src/database/data/accommodation-categories-v2.data.ts
  src/database/migrations/1734374876753-add-russian-to-category-amenity.ts
  src/modules/accommodations/accommodations.controller.ts
  src/modules/accommodations/accommodations.service.ts
  src/modules/accommodations/test/accommodations.controller.spec.ts
  src/modules/amenities/amenities.controller.ts
  src/modules/amenities/amenities.service.ts
  src/modules/amenities/entities/amenity.entity.ts
  src/modules/amenities/test/amenities.controller.spec.ts
  src/modules/categories/entities/category.entity.ts
Labels: enhancement

#65 [FEAT]: Added support for avif files
  src/modules/accommodations/pipes/accommodation-images-validation.pipe.ts
Labels: bug, enhancement

#64 fix: styling on notification
  src/modules/mail/mail.service.ts
Labels: bug

#66 [FIX-86]: Fixed validator, price and check-in/check-out bug in bookings module
  src/modules/bookings/bookings.service.ts
  src/shared/validators/is-future-date.validator.ts
Labels: bug

#68 [FIX-88]: Fixed problem with search logic for booking dates
  src/modules/accommodations/accommodations.service.ts
Labels: bug

#71 [FIX-92]: Handle payment for today's booking
  src/modules/stripe/stripe.service.ts
Labels: enhancement

#72 [FIX-91]: Fix stripe checkout error for prices
  src/shared/helpers/convert-to-cent.ts
Labels: bug

#74 [FIX-93]: Added notifications for status change in cronjob
  src/modules/bookings/bookings.service.ts
  src/modules/bookings/tests/bookings.service.spec.ts
Labels: bug

#79 [FEAT-97]: Added caching for amenities and categories
  src/modules/amenities/amenities.module.ts
  src/modules/amenities/amenities.service.ts
  src/modules/amenities/test/amenities.service.spec.ts
  src/modules/categories/categories.module.ts
  src/modules/categories/categories.service.ts
  src/modules/categories/test/categories.service.spec.ts
Labels: enhancement
